#!/bin/bash

usage() {
	echo "Usage: createSuiteFile {1: suite file} {2: test name} [3: test name index bound]"
}

if [ ${#} -eq 2 ]; then
	suite=${1}
	testname=${2}
	((bound=40))
elif [ ${#} -eq 3 ]; then
	suite=${1}
	testname=${2}
	((bound=${3}))
else
	usage
	exit 1
fi

if [ -d ${suite} ]; then
	usage
	echo "Given \"suite file\" is a directory"
	exit 1
elif [ -e ${suite} -a ! -r ${suite} ]; then
	usage
	echo "Given suite file is not readable"
	exit 1
elif [ -e ${suite} -a ! -w ${suite} ]; then
	usage
	echo "Given suite file is not writable"
	exit 1
fi


echo -n "" > ${suite}
for (( i=1; i<=${bound}; ++i )) do
	echo "${testname}${i}" >> ${suite}
done
